name: gnn
channels:
  - pytorch
  - dglteam
  - pyg
  - conda-forge
dependencies:
  - pip
  - tqdm
  - pyyaml
  - numpy
  - scikit-learn
  - graph-tool
  - cudatoolkit=11.3
  - pytorch
  - dgl-cuda11.3
  - pyg
  - pip:
    - ogb
    - graphrole
    - git+https://github.com/qema/orca-py.git
